# Generated by Django 3.1.2 on 2021-08-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Image', models.ImageField(default='null', upload_to='Images')),
                ('Second_Image', models.ImageField(default='null', upload_to='Images')),
                ('Third_Image', models.ImageField(default='null', upload_to='Images')),
                ('Fourth_Image', models.ImageField(default='null', upload_to='Images')),
                ('Fifth_Image', models.ImageField(default='null', upload_to='Images')),
                ('Sixth_Image', models.ImageField(default='null', upload_to='Images')),
                ('Property_Short_Name', models.TextField(max_length=300)),
                ('Property_Full_Name', models.TextField(max_length=1000)),
                ('Property_Short_address', models.TextField(max_length=1500)),
                ('Property_Full_Address', models.TextField(max_length=2500)),
                ('Property_Type_Place', models.TextField(max_length=300)),
                ('Property_bedrooms', models.IntegerField()),
                ('Property_Bathrooms', models.IntegerField()),
                ('Property_Max_Occupancy', models.IntegerField()),
                ('Property_About_Text', models.TextField(max_length=10000)),
                ('Property_City', models.TextField(max_length=100)),
                ('Property_Area', models.TextField(max_length=1000)),
                ('Property_State', models.TextField(max_length=200)),
                ('Property_PricePer_Night', models.IntegerField()),
                ('Property_Price_At_Weekend', models.IntegerField()),
                ('Minimum_length_to_stay', models.IntegerField()),
                ('Property_ID', models.IntegerField()),
                ('Property_Size', models.IntegerField()),
                ('CheckIn_Hour', models.TimeField()),
                ('CheckOut_Hour', models.TimeField()),
            ],
        ),
    ]
